project:
  type: website
  output-dir: _build

website:
  title: "mlogs"
  favicon: favicon.png
  navbar:
    right:
      - text: "Home"
        href: http://www.nottherealsanta.com
      - icon: github
        href: https://github.com/nottherealsanta
      - icon: twitter
        href: https://x.com/nottherealsanta
format:
  html:
    page-layout: article
    theme: 
      light: light.scss
      dark: dark.scss
    css: styles.css



